tap "domt4/autoupdate"

brew "agent-browser"
brew "bat"
brew "colordiff"
brew "difftastic"
brew "defaultbrowser"
brew "dockutil"
brew "fd"
brew "gh"
brew "glow"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-lfs"
brew "mas"
brew "mise"
brew "neovim"
brew "opencode"
brew "playwright-cli"
brew "ripgrep"
brew "skills"
brew "terminal-notifier"
brew "tldr"
brew "vim"
brew "watchman"
brew "wget"
brew "xdg-ninja", args: ["HEAD"]
brew "jandedobbeleer/oh-my-posh/oh-my-posh"

cask "1password"
cask "chatgpt"
cask "chromium"
cask "claude-code"
cask "cloudflare-warp"
cask "codex"
cask "docker-desktop"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "ngrok"
cask "obsidian"

mas "Monosnap", id: 540348655
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
